"""
3GPP 5G CDL Channel Generator using Sionna 0.13.0

Generates wireless propagation channel according to 3GPP 5G CDL model.
Supports two antenna configurations:
  - 'massive_mimo': 256 BS (8x16 dual-pol VH, 38.901) + 2 UE antennas (1x2 dual-pol VH)
  - 'omni_2x1':     2 BS (1x2 single-pol omni)        + 1 UE antenna  (1x1 single-pol omni)
Requires: sionna==0.13.0, tensorflow, numpy
"""
import pickle
import numpy as np
import tensorflow as tf

# Sionna 0.13.0
import sionna as sn
from sionna.channel.tr38901 import CDL, AntennaArray
from sionna.channel.utils import cir_to_ofdm_channel, subcarrier_frequencies

# --- Common parameters ---
CARRIER_FREQ = 3.5e9
N_OFDM = 12
N_UE = 16
N_SC = 192
SUBCARRIER_SPACING = 30e3
DELAY_SPREAD = 100e-9
UE_SPEED_MIN = 100.0 / 3.6
UE_SPEED_MAX = 300.0 / 3.6
SEED = 42

# --- Select antenna preset here ---
ANTENNA_SETUP = "massive_mimo"        # "massive_mimo" or "omni_2x1"

# --- Select channel-model list here ---
# Each user channel is generated by randomly choosing one model from the selected list.
CDL_MODEL_LISTS = {
    "only_B": ["B"],
    "only_C": ["C"],
    "only_D": ["D"],
    "B_C_D": ["B", "C", "D"],
    "B_C": ["B", "C"],
    "C_D": ["C", "D"],
}
CDL_MODEL_LIST_SELECT = "B_C_D"   # choose one key from CDL_MODEL_LISTS

# --- Antenna presets ---
ANTENNA_PRESETS = {
    "massive_mimo": {
        "pkl_name": "cdl_channel_Hfr_new.pkl",
        "bs_num_rows": 8,
        "bs_num_cols": 16,
        "bs_polarization": "dual",
        "bs_polarization_type": "VH",
        "bs_antenna_pattern": "38.901",
        "bs_vert_spacing": 1.0,
        "bs_horiz_spacing": 0.5,
        "ue_num_rows": 1,
        "ue_num_cols": 2,
        "ue_polarization": "dual",
        "ue_polarization_type": "VH",
        "ue_antenna_pattern": "38.901",
        "ue_vert_spacing": 0.5,
        "ue_horiz_spacing": 0.5,
        "n_ue_ant": 2,
    },
    "omni_2x1": {
        "pkl_name": "cdl_channel_Hfr_2x1.pkl",
        "bs_num_rows": 1,
        "bs_num_cols": 2,
        "bs_polarization": "single",
        "bs_polarization_type": "V",
        "bs_antenna_pattern": "omni",
        "bs_vert_spacing": 0.5,
        "bs_horiz_spacing": 0.5,
        "ue_num_rows": 1,
        "ue_num_cols": 1,
        "ue_polarization": "single",
        "ue_polarization_type": "V",
        "ue_antenna_pattern": "omni",
        "ue_vert_spacing": 0.5,
        "ue_horiz_spacing": 0.5,
        "n_ue_ant": 1,
    },
}


def create_bs_array(preset):
    return AntennaArray(
        num_rows=preset["bs_num_rows"],
        num_cols=preset["bs_num_cols"],
        polarization=preset["bs_polarization"],
        polarization_type=preset["bs_polarization_type"],
        antenna_pattern=preset["bs_antenna_pattern"],
        carrier_frequency=CARRIER_FREQ,
        vertical_spacing=preset["bs_vert_spacing"],
        horizontal_spacing=preset["bs_horiz_spacing"],
    )


def create_ue_array(preset):
    return AntennaArray(
        num_rows=preset["ue_num_rows"],
        num_cols=preset["ue_num_cols"],
        polarization=preset["ue_polarization"],
        polarization_type=preset["ue_polarization_type"],
        antenna_pattern=preset["ue_antenna_pattern"],
        carrier_frequency=CARRIER_FREQ,
        vertical_spacing=preset["ue_vert_spacing"],
        horizontal_spacing=preset["ue_horiz_spacing"],
    )


def compute_n_ant(num_rows, num_cols, polarization):
    """Number of antenna elements: rows * cols * (2 if dual-pol else 1)."""
    pol_factor = 2 if polarization == "dual" else 1
    return num_rows * num_cols * pol_factor


def main():
    preset = ANTENNA_PRESETS[ANTENNA_SETUP]
    output_pkl = preset["pkl_name"]
    model_pool = CDL_MODEL_LISTS[CDL_MODEL_LIST_SELECT]
    if len(model_pool) == 0:
        raise ValueError("Selected CDL model list is empty.")
    for m in model_pool:
        if m not in {"A", "B", "C", "D", "E"}:
            raise ValueError(f"Unsupported CDL model '{m}' in selected list.")

    rng = np.random.default_rng(SEED)
    cdl_cache = {}

    n_bs_ant = compute_n_ant(preset["bs_num_rows"], preset["bs_num_cols"],
                             preset["bs_polarization"])
    n_ue_ant = preset["n_ue_ant"]

    print("Sionna version:", sn.__version__)
    print(f"Antenna config : {ANTENNA_SETUP}")
    print(f"CDL model list : {CDL_MODEL_LIST_SELECT} -> {model_pool}")
    print(f"  BS antennas  : {n_bs_ant}  ({preset['bs_num_rows']}x{preset['bs_num_cols']}, "
          f"{preset['bs_polarization']}-pol, {preset['bs_antenna_pattern']})")
    print(f"  UE antennas  : {n_ue_ant}  ({preset['ue_num_rows']}x{preset['ue_num_cols']}, "
          f"{preset['ue_polarization']}-pol, {preset['ue_antenna_pattern']})")

    sampling_frequency = N_SC * SUBCARRIER_SPACING
    bs_array = create_bs_array(preset)
    ue_array = create_ue_array(preset)

    frequencies = subcarrier_frequencies(N_SC, SUBCARRIER_SPACING)

    Hfr_list = []
    for u in range(N_UE):
        model_u = rng.choice(model_pool)
        if model_u not in cdl_cache:
            cdl_cache[model_u] = CDL(
                model=model_u,
                delay_spread=DELAY_SPREAD,
                carrier_frequency=CARRIER_FREQ,
                ut_array=ue_array,
                bs_array=bs_array,
                direction='uplink',
                min_speed=UE_SPEED_MIN,
                max_speed=UE_SPEED_MAX,
            )
        cdl_u = cdl_cache[model_u]

        a, tau = cdl_u(
            batch_size=1,
            num_time_steps=N_OFDM,
            sampling_frequency=sampling_frequency,
        )
        H_user = cir_to_ofdm_channel(frequencies, a, tau, normalize=False)
        # H_user: (1, 1, N_bs_ant, 1, N_ue_ant_total, N_ofdm, N_sc)
        Hu = H_user[0, 0, :, 0, :, :, :].numpy()  # (N_bs_ant, N_ue_ant_total, N_ofdm, N_sc)
        Hfr_list.append(Hu)

    Hfr_list_proc = []
    for u in range(N_UE):
        Hu = Hfr_list[u]  # (N_bs_ant, N_ue_ant_total, N_ofdm, N_sc)
        Hu = np.transpose(Hu, (2, 1, 0, 3))  # (N_ofdm, N_ue_ant_total, N_bs_ant, N_sc)
        Hu = Hu[:, :n_ue_ant, :, :]
        Hfr_list_proc.append(Hu)
    Hfr = np.stack(Hfr_list_proc, axis=1)
    # Hfr: (N_ofdm, N_ue, N_ue_ant, N_bs_ant, N_sc)
    print("Hfr shape:", Hfr.shape)

    with open(output_pkl, "wb") as f:
        pickle.dump(Hfr, f)
    print("Saved to", output_pkl)


if __name__ == "__main__":
    main()
